routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::resource('room-type', 'RoomTypeController');
Route::get('room_type/{department}', 'RoomTypeController@destroy')->name('room-type.delete');

Route::resource('payment', 'PaymentController');
Route::get('payment_destroy/{department}', 'PaymentController@destroy')->name('payment.delete');

Route::resource('room-setup', 'RoomSetupController');
Route::get('room_setup/{department}', 'RoomSetupController@destroy')->name('room-setup.delete');

Route::resource('booking', 'BookingController');
Route::get('booking_delete/{department}', 'BookingController@destroy')->name('booking.delete');
Route::get('booking-schedule', 'BookingController@schedule')->name('booking.schedule');
Route::get('new-booking', 'BookingController@NewBook')->name('new_booking');
Route::get('room-rent', 'BookingController@RoomRent')->name('room.rent');

Route::resource('booking-request', 'BookingRequestController');
Route::get('booking-request/{data}/{data2}', 'BookingRequestController@accept')->name('booking.accept');
Route::get('booking-reject/{data}', 'BookingRequestController@reject')->name('booking.reject');
Route::get('booking_request_delete/{department}', 'BookingRequestController@destroy')->name('booking.request.delete');

resources/views/inc/footer.blade.php
<footer class="main-footer d-flex p-2 px-3 bg-white border-top">
    <span class="copyright ml-auto my-auto mr-2">Copyright © 2019 Army Golf Club, Dhaka Cantonment.</span>
</footer>

resources/views/inc/header.blade.php
<div class="main-navbar sticky-top bg-white">
    <!-- Main Navbar -->
    <nav class="navbar align-items-stretch navbar-light flex-md-nowrap p-0">

        <ul class="navbar-nav border-left flex-row ">

        </ul>
        <nav class="nav">
            <a href="#"
               class="nav-link nav-link-icon toggle-sidebar d-sm-inline d-md-none text-center border-left"
               data-toggle="collapse" data-target=".header-navbar" aria-expanded="false"
               aria-controls="header-navbar">
                <i class="material-icons">&#xE5D2;</i>
            </a>
        </nav>
    </nav>
</div> <!-- / .main-navbar -->

resources/views/inc/sidebar.blade.php
<!-- Main Sidebar -->
<aside class="main-sidebar col-12 col-md-3 col-lg-2 px-0" style="z-index: 1040">
    <div class="main-navbar">
        <nav class="navbar align-items-stretch navbar-light bg-white flex-md-nowrap border-bottom p-0">
            <a class="navbar-brand w-100 mr-0" href="{{route('home')}}" style="line-height: 25px;">
                <div class="d-table m-auto">
                    <img id="main-logo" class="d-inline-block align-top mr-1" style="max-width: 25px;"
                         src="{{asset('assets/images/logo.jpg')}}" alt="Store Inventory">
                    <span class="d-none d-md-inline ml-1">Guest Room Man.</span>
                </div>
            </a>
            <a class="toggle-sidebar d-sm-inline d-md-none d-lg-none">
                <i class="material-icons">&#xE5C4;</i>
            </a>
        </nav>
    </div>
    <form action="#" class="main-sidebar__search w-100 border-right d-sm-flex d-md-none d-lg-none">
        <div class="input-group input-group-seamless ml-3">
            <div class="input-group-prepend">
                <div class="input-group-text">
                    <i class="fas fa-search"></i>
                </div>
            </div>
            <input class="navbar-search form-control" type="text" placeholder="Search for something..."
                   aria-label="Search">
        </div>
    </form>
    <div class="nav-wrapper">
        <ul class="nav nav--no-borders flex-column">
            <li class="nav-item">
                <a class="nav-link" href="{{route('home')}}">
                    <i class="fas fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('booking-request.index')}}">
                    <i class="material-icons">&#xE917;</i>
                    <span>Booking Request List</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('booking.index')}}">
                    <i class="material-icons">&#xE917;</i>
                    <span>Booking</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('booking.schedule')}}">
                    <i class="material-icons">&#xE917;</i>
                    <span>Booking Schedule</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('payment.index')}}">
                    <i class="material-icons">&#xE917;</i>
                    <span>Payment</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('room-type.index')}}">
                    <i class="material-icons">&#xE917;</i>
                    <span>Room Type</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('room-setup.index')}}">
                    <i class="material-icons">&#xE917;</i>
                    <span>Room Setup</span>
                </a>
            </li>
        </ul>
    </div>
</aside>
<!-- End Main Sidebar -->